
CREATE TABLE CARNE_ESTUDIANTE
(
  CARESTINST         VARCHAR2(100 BYTE),
  CARESTINSTCODDANE  NUMBER(12),
  CARESTSEDE         VARCHAR2(150 BYTE),
  CARESTJORN         VARCHAR2(100 BYTE),
  CARESTAPELLIDOS    VARCHAR2(60 BYTE),
  CARESTNOMBRES      VARCHAR2(60 BYTE),
  CARESTNUMDOC       VARCHAR2(20 BYTE),
  CARESTCODGRADO     NUMBER(3),
  CARESTGRADO        VARCHAR2(60 BYTE),
  CARESTCODIGO       NUMBER(11),
  CARESTANO          NUMBER(4),
  CARESTNOMRECTOR    VARCHAR2(100 BYTE),
  CARESTAPERECTOR    VARCHAR2(100 BYTE),
  CARESTID           NUMBER(12),
  CARESTCODGRUPO     NUMBER(3),
  CARESTGRUPO        VARCHAR2(60 BYTE),
  CARESTTIPDOC       VARCHAR2(20 BYTE),
  CARESTFECNAC       DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX IND_CARNE ON CARNE_ESTUDIANTE
(CARESTID)
LOGGING
NOPARALLEL;



