CREATE OR REPLACE TRIGGER TRG_insertAlumno AFTER INSERT ON ALUMNO
	FOR EACH ROW
	BEGIN
		Pk_Integracion_Mat_Apoyo.insertAlumno2(
		:NEW.AL_CODI_ID,:NEW.AL_AO_ESTA,
		:NEW.IN_CODI_ID,
		:NEW.JR_CODI_ID,
		NVL(:NEW.GR_CODI_ID,-9),
		NVL(:NEW.GP_CODI_ID,0),
		TO_NUMBER(NVL(:NEW.DD_CODI_ID_EXPU,'-9')), 
		TO_NUMBER(NVL(:NEW.DM_CODI_ID_EXPU,'-9')),
		:NEW.TI_CODI_ID,
		:NEW.AL_NUME_ID,
		:NEW.AL_PRIM_APEL,
		:NEW.AL_SEGU_APEL,
		:NEW.AL_PRIM_NOMB,
		:NEW.AL_SEGU_NOMB,
		:NEW.ES_CODI_ID,
		(CASE UPPER(:NEW.AL_GENE) WHEN 'M' THEN 1 ELSE 2 END),
		TO_CHAR(:NEW.AL_FECH_NACI,'dd/mm/yyyy'),
		TO_NUMBER(NVL(:NEW.DD_CODI_ID_NACE,'-9')), 
		TO_NUMBER(NVL(:NEW.DM_CODI_ID_NACE,'-9')));
	END;