CREATE OR REPLACE TRIGGER TRG_updateUbicacionAlumno AFTER UPDATE OF
IN_CODI_ID,
JR_CODI_ID,
GR_CODI_ID,
GP_CODI_ID
ON ALUMNO
	FOR EACH ROW
	BEGIN
		Pk_Integracion_Mat_Apoyo.updateAlumno2(
		:NEW.AL_CODI_ID,:NEW.AL_AO_ESTA,
		:NEW.IN_CODI_ID,
		:NEW.JR_CODI_ID,
		NVL(:NEW.GR_CODI_ID,-9),
		NVL(:NEW.GP_CODI_ID,0),
		:NEW.TI_CODI_ID,
		:NEW.AL_NUME_ID,
		:NEW.ES_CODI_ID,
		:OLD.IN_CODI_ID,
		:OLD.JR_CODI_ID,
		NVL(:OLD.GR_CODI_ID,-9),
		NVL(:OLD.GP_CODI_ID,0));
	END;