CREATE OR REPLACE TRIGGER TRG_updateIdAlumno AFTER UPDATE OF
AL_PRIM_APEL,
AL_SEGU_APEL,
AL_PRIM_NOMB,
AL_SEGU_NOMB,
DD_CODI_ID_EXPU,
DM_CODI_ID_EXPU,
AL_GENE
ON ALUMNO
	FOR EACH ROW
	BEGIN
		Pk_Integracion_Mat_Apoyo.updateIdAlumno2(
		:NEW.AL_CODI_ID,
		:NEW.AL_AO_ESTA,
		:NEW.TI_CODI_ID,
		:NEW.AL_NUME_ID,
		:NEW.AL_PRIM_APEL,
		:NEW.AL_SEGU_APEL,
		:NEW.AL_PRIM_NOMB,
		:NEW.AL_SEGU_NOMB,
		:NEW.ES_CODI_ID,
		TO_NUMBER(NVL(:NEW.DD_CODI_ID_EXPU,'0')),
		TO_NUMBER(NVL(:NEW.DM_CODI_ID_EXPU,'0')),
		(CASE UPPER(:NEW.AL_GENE) WHEN 'M' THEN 1 ELSE 2 END)
		);
		
	END;