fotografia.pathSubir=WEB-INF.private.upload.temp
fotografia.temporal=WEB-INF.private.temp

foto.actualizar = UPDATE ESTUDIANTE SET ESTFOTO=? WHERE ESTCODIGO=?
foto.actualizarPersonal =  UPDATE PERSONAL SET PERFOTO= ? WHERE PERTIPDOCUM=? AND PERNUMDOCUM=? 
foto.longitud=30720

#Ruta anterior para fotos estudiante (Bug 2024-02-17)
#foto.pathSubir=WEB-INF.private.fotoEstudiante
#Ruta nueva para fotos estudiante (Bug 2024-02-17)
foto.pathSubir=private.fotoEstudiante


