CREATE OR REPLACE PACKAGE PK_DUPLICACION AS
	PROCEDURE duplicarAsignatura(id in NUMERIC,inst in NUMERIC,met in NUMERIC,anhoVigenciaOld in NUMERIC,perVigenciaOld in NUMERIC,anhoVigenciaNew in NUMERIC,perVigencianew in NUMERIC);
	PROCEDURE duplicarGrupo(id in NUMERIC,inst in NUMERIC,met in NUMERIC,anhoVigenciaOld in NUMERIC,perVigenciaOld in NUMERIC,anhoVigenciaNew in NUMERIC,perVigencianew in NUMERIC);
	PROCEDURE duplicarHorario(id in NUMERIC,inst in NUMERIC,met in NUMERIC,anhoVigenciaOld in NUMERIC,perVigenciaOld in NUMERIC,anhoVigenciaNew in NUMERIC,perVigencianew in NUMERIC);
END PK_DUPLICACION;
/

CREATE OR REPLACE PACKAGE BODY PK_DUPLICACION AS
  PROCEDURE duplicarAsignatura(id in NUMERIC,inst in NUMERIC,met in NUMERIC,anhoVigenciaOld in NUMERIC,perVigenciaOld in NUMERIC,anhoVigenciaNew in NUMERIC,perVigencianew in NUMERIC) IS
	cont number(6);
	maximo number(6);
	CURSOR cursor_asig IS
	SELECT * FROM ART_ASIGNATURA where ARTASIGCODINST=inst and ARTASIGCODMETOD=met and ARTASIGANOVIGENCIA=anhoVigenciaOld and ARTASIGPERVIGENCIA=perVigenciaOld;
	BEGIN
		cont:=0;
		maximo:=0;
		SELECT nvl(max(ARTASIGCODIGO),0) into maximo FROM ART_ASIGNATURA;
		FOR rec in cursor_asig LOOP
			maximo:=maximo+1;
			INSERT INTO ART_HIST_DUP_ASIG(HISTDUPANHOVIGENCIAOLD, HISTDUPPERVIGENCIAOLD, HISTDUPANHOVIGENCIANEW, HISTDUPPERVIGENCIANEW, HISTDUPASIGNATURAOLD, HISTDUPASIGNATURANEW) 
			VALUES (anhoVigenciaOld,perVigenciaOld,anhoVigenciaNew,perVigenciaNew,rec.ARTASIGCODIGO,maximo);
			INSERT INTO ART_ASIGNATURA (
			   ARTASIGCODINST, ARTASIGCODMETOD, ARTASIGANOVIGENCIA, 
			   ARTASIGPERVIGENCIA, ARTASIGCODIGO, ARTASIGCOMPONENTE, 
			   ARTASIGCOM, ARTASIGCODESP, ARTASIGCODAREA, 
			   ARTASIGTIPPERIODO, ARTASIGNUMPERIODO, ARTASIGCODASIG, 
			   ARTASIGNOMBRE, ARTASIGCODASIGINST, ARTASIGABREVIATURA, 
			   ARTASIGINTHORARIA, ARTASIGCREDITO, ARTASIGSESION, 
			   ARTASIGHABILITABLE, ARTASIGDESCRIPCION, ARTASIGORDEN, 
			   ARTASIGHOMOLOGAR, ARTASIGNOTMINHOM, ARTASIGTIP, 
			   ARTASIGNAT, ARTASIGMOD, ARTASIGCLASCONSEC) 
			VALUES (rec.ARTASIGCODINST, rec.ARTASIGCODMETOD, anhoVigenciaNew, 
					perVigenciaNew, maximo, rec.ARTASIGCOMPONENTE, 
					rec.ARTASIGCOM, rec.ARTASIGCODESP, rec.ARTASIGCODAREA, 
					rec.ARTASIGTIPPERIODO, rec.ARTASIGNUMPERIODO, rec.ARTASIGCODASIG, 
					rec.ARTASIGNOMBRE, rec.ARTASIGCODASIGINST, rec.ARTASIGABREVIATURA, 
					rec.ARTASIGINTHORARIA, rec.ARTASIGCREDITO, rec.ARTASIGSESION, 
	   			  rec.ARTASIGHABILITABLE, rec.ARTASIGDESCRIPCION, rec.ARTASIGORDEN, 
	   			  rec.ARTASIGHOMOLOGAR, rec.ARTASIGNOTMINHOM, rec.ARTASIGTIP, 
	   			  rec.ARTASIGNAT, rec.ARTASIGMOD, rec.ARTASIGCLASCONSEC);
		END LOOP;	
		--PONER COMPLEMENTARIAS     
			INSERT INTO ART_ASIGNATURA_COMPLEMENTARIA (ASIGCODIGO, ASIGCOMCODIGO) 
			SELECT a.HISTDUPASIGNATURANEW,b.HISTDUPASIGNATURANEW
			FROM ART_ASIGNATURA_COMPLEMENTARIA,ART_HIST_DUP_ASIG a,ART_HIST_DUP_ASIG b
			where a.HISTDUPANHOVIGENCIAOLD=anhoVigenciaOld
			and a.HISTDUPPERVIGENCIAOLD=perVigenciaOld
			and a.HISTDUPANHOVIGENCIANEW=anhoVigenciaNew
			and a.HISTDUPPERVIGENCIANEW=perVigenciaNew
			and a.HISTDUPASIGNATURAOLD=ASIGCODIGO
			and b.HISTDUPANHOVIGENCIAOLD=anhoVigenciaOld
			and b.HISTDUPPERVIGENCIAOLD=perVigenciaOld
			and b.HISTDUPANHOVIGENCIANEW=anhoVigenciaNew
			and b.HISTDUPPERVIGENCIANEW=perVigenciaNew
			and b.HISTDUPASIGNATURAOLD=ASIGCOMCODIGO
			and ASIGCODIGO in(SELECT ARTASIGCODIGO FROM ART_ASIGNATURA where ARTASIGCODINST=inst and ARTASIGCODMETOD=met and ARTASIGANOVIGENCIA=anhoVigenciaOld and ARTASIGPERVIGENCIA=perVigenciaOld);		
		--PONER PRERREQUISISTOS      
			INSERT INTO ART_ASIGNATURA_PREREQ (ASIGCODIGO, ASIGPRECODIGO) 
			SELECT a.HISTDUPASIGNATURANEW,b.HISTDUPASIGNATURANEW
			FROM ART_ASIGNATURA_PREREQ,ART_HIST_DUP_ASIG a,ART_HIST_DUP_ASIG b
			where a.HISTDUPANHOVIGENCIAOLD=anhoVigenciaOld
			and a.HISTDUPPERVIGENCIAOLD=perVigenciaOld
			and a.HISTDUPANHOVIGENCIANEW=anhoVigenciaNew
			and a.HISTDUPPERVIGENCIANEW=perVigenciaNew
			and a.HISTDUPASIGNATURAOLD=ASIGCODIGO
			and b.HISTDUPANHOVIGENCIAOLD=anhoVigenciaOld
			and b.HISTDUPPERVIGENCIAOLD=perVigenciaOld
			and b.HISTDUPANHOVIGENCIANEW=anhoVigenciaNew
			and b.HISTDUPPERVIGENCIANEW=perVigenciaNew
			and b.HISTDUPASIGNATURAOLD=ASIGPRECODIGO
			and ASIGCODIGO in(SELECT ARTASIGCODIGO FROM ART_ASIGNATURA where ARTASIGCODINST=inst and ARTASIGCODMETOD=met and ARTASIGANOVIGENCIA=anhoVigenciaOld and ARTASIGPERVIGENCIA=perVigenciaOld);	
		--PONER CORREQUISITOS      
			INSERT INTO ART_ASIGNATURA_COREQ (ASIGCODIGO, ASIGCORCODIGO) 
			SELECT a.HISTDUPASIGNATURANEW,b.HISTDUPASIGNATURANEW
			FROM ART_ASIGNATURA_COREQ,ART_HIST_DUP_ASIG a,ART_HIST_DUP_ASIG b
			where a.HISTDUPANHOVIGENCIAOLD=anhoVigenciaOld
			and a.HISTDUPPERVIGENCIAOLD=perVigenciaOld
			and a.HISTDUPANHOVIGENCIANEW=anhoVigenciaNew
			and a.HISTDUPPERVIGENCIANEW=perVigenciaNew
			and a.HISTDUPASIGNATURAOLD=ASIGCODIGO
			and b.HISTDUPANHOVIGENCIAOLD=anhoVigenciaOld
			and b.HISTDUPPERVIGENCIAOLD=perVigenciaOld
			and b.HISTDUPANHOVIGENCIANEW=anhoVigenciaNew
			and b.HISTDUPPERVIGENCIANEW=perVigenciaNew
			and b.HISTDUPASIGNATURAOLD=ASIGCORCODIGO
			and ASIGCODIGO in(SELECT ARTASIGCODIGO FROM ART_ASIGNATURA where ARTASIGCODINST=inst and ARTASIGCODMETOD=met and ARTASIGANOVIGENCIA=anhoVigenciaOld and ARTASIGPERVIGENCIA=perVigenciaOld);
	---EXCEPTION
	--WHEN others THEN
		--RAISE_APPLICATION_ERROR (500, 'Error interno duplicarAsignatura');
  END duplicarAsignatura;
	

  PROCEDURE duplicarGrupo(id in NUMERIC,inst in NUMERIC,met in NUMERIC,anhoVigenciaOld in NUMERIC,perVigenciaOld in NUMERIC,anhoVigenciaNew in NUMERIC,perVigencianew in NUMERIC) IS
	cont number(6);
	maximo number(6);
	CURSOR cursor_grupo IS
	SELECT * FROM ART_GRUPO	where ARTGRUCODINST=inst and ARTGRUANOVIGENCIA=anhoVigenciaOld and ARTGRUPERVIGENCIA=perVigenciaOld;
	BEGIN
		cont:=0;
		maximo:=0;
		SELECT nvl(max(ARTGRUCODIGO),0) into maximo FROM ART_GRUPO;
		FOR rec in cursor_grupo LOOP
			maximo:=maximo+1;
			INSERT INTO ART_HIST_DUP_GRUPO (HISTDUPANHOVIGENCIAOLD, HISTDUPPERVIGENCIAOLD, HISTDUPANHOVIGENCIANEW, HISTDUPPERVIGENCIANEW, HISTDUPGRUPOOLD, HISTDUPGRUPONEW) 
			VALUES (anhoVigenciaOld,perVigenciaOld,anhoVigenciaNew,perVigenciaNew,rec.ARTGRUCODIGO,maximo);
			INSERT INTO ART_GRUPO (
			   ARTGRUCODINST, ARTGRUCODSEDE, ARTGRUCODJORNADA, 
			   ARTGRUANOVIGENCIA, ARTGRUPERVIGENCIA, ARTGRUPERESP, 
			   ARTGRUCOMPONENTE, ARTGRUCODESP, ARTGRUCODIGO, 
			   ARTGRUCONSECUTIVO, ARTGRUREPITE, ARTGRUORDEN, 
			   ARTGRUCUPONIVEL, ARTGRUCUPONONIVEL, ARTGRUCUPOGENERAL) 
			VALUES (
				rec.ARTGRUCODINST, rec.ARTGRUCODSEDE, rec.ARTGRUCODJORNADA, 
				anhoVigenciaNew, perVigenciaNew, rec.ARTGRUPERESP, 
				rec.ARTGRUCOMPONENTE, rec.ARTGRUCODESP, maximo, 
				rec.ARTGRUCONSECUTIVO, rec.ARTGRUREPITE, rec.ARTGRUORDEN, 
				rec.ARTGRUCUPONIVEL, rec.ARTGRUCUPONONIVEL, rec.ARTGRUCUPOGENERAL			
			);			
			
		END LOOP;	
		--GRUPO ASIGNATURA      
			INSERT INTO ART_GRUPO_ASIGNATURA (ARTGRUASICODGRUPO, ARTGRUASICODASIG) 
			SELECT a.HISTDUPGRUPONEW,b.HISTDUPASIGNATURANEW
			FROM ART_GRUPO_ASIGNATURA,ART_HIST_DUP_GRUPO a,ART_HIST_DUP_ASIG b
			where a.HISTDUPANHOVIGENCIAOLD=anhoVigenciaOld 
			and a.HISTDUPPERVIGENCIAOLD=perVigenciaOld
			and a.HISTDUPANHOVIGENCIANEW=anhoVigenciaNew 
			and a.HISTDUPPERVIGENCIANEW=perVigenciaNew
			and a.HISTDUPGRUPOOLD=ARTGRUASICODGRUPO
			and b.HISTDUPANHOVIGENCIAOLD=anhoVigenciaOld
			and b.HISTDUPPERVIGENCIAOLD=perVigenciaOld
			and b.HISTDUPANHOVIGENCIANEW=anhoVigenciaNew
			and b.HISTDUPPERVIGENCIANEW=perVigenciaNew
			and b.HISTDUPASIGNATURAOLD=ARTGRUASICODASIG
			and ARTGRUASICODGRUPO in(SELECT ARTGRUCODIGO FROM ART_GRUPO WHERE ARTGRUCODINST=inst and ARTGRUANOVIGENCIA=perVigenciaOld and ARTGRUPERVIGENCIA=anhoVigenciaOld);
	--EXCEPTION
	--WHEN others THEN
	--	RAISE_APPLICATION_ERROR (500, 'Error interno duplicarGrupo');
  END duplicarGrupo;


  PROCEDURE duplicarHorario(id in NUMERIC,inst in NUMERIC,met in NUMERIC,anhoVigenciaOld in NUMERIC,perVigenciaOld in NUMERIC,anhoVigenciaNew in NUMERIC,perVigencianew in NUMERIC) IS
	cont number(6);
	maximo number(6);
	CURSOR cursor_horario IS
	SELECT * FROM ART_PARAM_HORARIO where ARTPARHORCODINST=inst and ARTPARHORANOVIGENCIA=anhoVigenciaOld and ARTPARHORPERVIGENCIA=perVigenciaOld;
	BEGIN
		cont:=0;
		maximo:=0;
		SELECT nvl(max(ARTPARHORCODIGO),0) into maximo FROM ART_PARAM_HORARIO;
		FOR rec in cursor_horario LOOP
			maximo:=maximo+1;
			INSERT INTO ART_HIST_DUP_HOR (HISTDUPANHOVIGENCIAOLD, HISTDUPPERVIGENCIAOLD, HISTDUPANHOVIGENCIANEW,HISTDUPPERVIGENCIANEW, HISTDUPHOROLD, HISTDUPHORNEW) 
			VALUES (anhoVigenciaOld,perVigenciaOld,anhoVigenciaNew,perVigenciaNew,rec.ARTPARHORCODIGO,maximo);

			INSERT INTO ART_PARAM_HORARIO (
			   ARTPARHORCODINST, ARTPARHORSEDE, ARTPARHORJORNADA, 
			   ARTPARHORANOVIGENCIA, ARTPARHORPERVIGENCIA, ARTPARHORCOMPONENTE, 
			   ARTPARHORSABADO, ARTPARHORDOMINGO, ARTPARHORAINI, 
			   ARTPARHORAMININI, ARTPARHORAFIN, ARTPARHORAMINFIN, 
			   ARTPARHORDURACLASE, ARTPARHORBLOQUE, ARTPARHORCLASEBLOQUE, 
			   ARTPARHORCODIGO, ARTPARHORNOMBRE) 
			VALUES (rec.ARTPARHORCODINST, rec.ARTPARHORSEDE, rec.ARTPARHORJORNADA, 
				anhoVigenciaNew, perVigenciaNew, rec.ARTPARHORCOMPONENTE, 
				rec.ARTPARHORSABADO, rec.ARTPARHORDOMINGO, rec.ARTPARHORAINI, 
				rec.ARTPARHORAMININI, rec.ARTPARHORAFIN, rec.ARTPARHORAMINFIN, 
				rec.ARTPARHORDURACLASE, rec.ARTPARHORBLOQUE, rec.ARTPARHORCLASEBLOQUE, 
				maximo, rec.ARTPARHORNOMBRE);			
		END LOOP;	
		--HORARIO   
			INSERT INTO ART_HORARIO (ARTHORAGRUPO, ARTHORADIA, ARTHORACLASE, 
			   ARTHORACODINST, ARTHORACODSEDE, ARTHORACODJORNADA, 
			   ARTHORAESPFISICO, ARTHORAASIGNATURA, ARTHORADOCENTE) 
			SELECT a.HISTDUPGRUPONEW, ARTHORADIA, ARTHORACLASE, 
			   ARTHORACODINST, ARTHORACODSEDE, ARTHORACODJORNADA, 
			   ARTHORAESPFISICO, b.HISTDUPASIGNATURANEW, ARTHORADOCENTE
			FROM ART_HORARIO,ART_HIST_DUP_GRUPO a,ART_HIST_DUP_ASIG b
			where a.HISTDUPANHOVIGENCIAOLD=anhoVigenciaOld 
			and a.HISTDUPPERVIGENCIAOLD=perVigenciaOld
			and a.HISTDUPANHOVIGENCIANEW=anhoVigenciaNew 
			and a.HISTDUPPERVIGENCIANEW=perVigenciaNew
			and a.HISTDUPGRUPOOLD=ARTHORAGRUPO
			and b.HISTDUPANHOVIGENCIAOLD=anhoVigenciaOld
			and b.HISTDUPPERVIGENCIAOLD=perVigenciaOld
			and b.HISTDUPANHOVIGENCIANEW=anhoVigenciaNew
			and b.HISTDUPPERVIGENCIANEW=perVigenciaNew
			and b.HISTDUPASIGNATURAOLD=ARTHORAASIGNATURA
			and ARTHORAGRUPO in(SELECT ARTGRUCODIGO FROM ART_GRUPO WHERE ARTGRUCODINST=inst and ARTGRUANOVIGENCIA=anhoVigenciaOld and ARTGRUPERVIGENCIA=perVigenciaOld);
	--EXCEPTION
	--WHEN others THEN
	--	RAISE_APPLICATION_ERROR (500, 'Error interno duplicarGrupo');
  END duplicarHorario;

  
END PK_DUPLICACION;
/

commit;

--select * from user_errors
	
	

