/*
 * Generated by JasperReports - 6/06/06 09:39 AM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import java.util.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class ReporteNo4 extends JRCalculator
{


    /**
     *
     */
    private JRFillParameter parameter_estudiante = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_usuario = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_escalas_valorativas = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;

    private JRFillField field_DETAREAPELLIDOS = null;
    private JRFillField field_DETARESEDE = null;
    private JRFillField field_DETAREID = null;
    private JRFillField field_DETAREJORNADA = null;
    private JRFillField field_DETARECODJERARAREA = null;
    private JRFillField field_DETAREAREA = null;
    private JRFillField field_DETARECODEVAL = null;
    private JRFillField field_DETARECODGRUPO = null;
    private JRFillField field_DETAREESTCODIGO = null;
    private JRFillField field_DETAREPERIODO = null;
    private JRFillField field_DETAREEVAL = null;
    private JRFillField field_DETAREGRADO = null;
    private JRFillField field_DETAREGRUPO = null;
    private JRFillField field_DETAREINSTITUCION = null;
    private JRFillField field_DETARENOMBRES = null;
    private JRFillField field_DETARECODGRADO = null;
    private JRFillField field_DETARENUMDOC = null;

    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_test = null;
    private JRFillVariable variable_SERIE_ESCALA32VALORATIVA = null;
    private JRFillVariable variable_SERIE_AREAS = null;
    private JRFillVariable variable_DETAREESTCODIGO_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        ) throws JRException
    {
        parameter_estudiante = (JRFillParameter)parsm.get("estudiante");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)parsm.get("REPORT_RESOURCE_BUNDLE");
        parameter_usuario = (JRFillParameter)parsm.get("usuario");
        parameter_REPORT_CONNECTION = (JRFillParameter)parsm.get("REPORT_CONNECTION");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)parsm.get("REPORT_PARAMETERS_MAP");
        parameter_escalas_valorativas = (JRFillParameter)parsm.get("escalas_valorativas");
        parameter_REPORT_LOCALE = (JRFillParameter)parsm.get("REPORT_LOCALE");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)parsm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)parsm.get("REPORT_SCRIPTLET");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)parsm.get("REPORT_MAX_COUNT");

        field_DETAREAPELLIDOS = (JRFillField)fldsm.get("DETAREAPELLIDOS");
        field_DETARESEDE = (JRFillField)fldsm.get("DETARESEDE");
        field_DETAREID = (JRFillField)fldsm.get("DETAREID");
        field_DETAREJORNADA = (JRFillField)fldsm.get("DETAREJORNADA");
        field_DETARECODJERARAREA = (JRFillField)fldsm.get("DETARECODJERARAREA");
        field_DETAREAREA = (JRFillField)fldsm.get("DETAREAREA");
        field_DETARECODEVAL = (JRFillField)fldsm.get("DETARECODEVAL");
        field_DETARECODGRUPO = (JRFillField)fldsm.get("DETARECODGRUPO");
        field_DETAREESTCODIGO = (JRFillField)fldsm.get("DETAREESTCODIGO");
        field_DETAREPERIODO = (JRFillField)fldsm.get("DETAREPERIODO");
        field_DETAREEVAL = (JRFillField)fldsm.get("DETAREEVAL");
        field_DETAREGRADO = (JRFillField)fldsm.get("DETAREGRADO");
        field_DETAREGRUPO = (JRFillField)fldsm.get("DETAREGRUPO");
        field_DETAREINSTITUCION = (JRFillField)fldsm.get("DETAREINSTITUCION");
        field_DETARENOMBRES = (JRFillField)fldsm.get("DETARENOMBRES");
        field_DETARECODGRADO = (JRFillField)fldsm.get("DETARECODGRADO");
        field_DETARENUMDOC = (JRFillField)fldsm.get("DETARENUMDOC");

        variable_PAGE_NUMBER = (JRFillVariable)varsm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)varsm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)varsm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)varsm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)varsm.get("COLUMN_COUNT");
        variable_test = (JRFillVariable)varsm.get("test");
        variable_SERIE_ESCALA32VALORATIVA = (JRFillVariable)varsm.get("SERIE_ESCALA VALORATIVA");
        variable_SERIE_AREAS = (JRFillVariable)varsm.get("SERIE_AREAS");
        variable_DETAREESTCODIGO_COUNT = (JRFillVariable)varsm.get("DETAREESTCODIGO_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 39 : // variable_test
            {
                value = (java.lang.String)("test");
                break;
            }
            case 49 : // textField_6
            {
                value = (java.lang.String)(((java.lang.String)field_DETARENUMDOC.getValue()));
                break;
            }
            case 51 : // textField_8
            {
                value = (java.lang.String)("EVALUACInN DE nREAS POR ESTUDIANTE PERIODO "+((java.lang.String)field_DETAREPERIODO.getValue()));
                break;
            }
            case 38 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 40 : // variableInitialValue_test
            {
                value = (java.lang.String)("test");
                break;
            }
            case 32 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 47 : // textField_4
            {
                value = (java.lang.String)(((java.lang.String)field_DETAREGRADO.getValue()));
                break;
            }
            case 59 : // textField_11
            {
                value = (java.lang.String)("Pngina " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()) + " de ");
                break;
            }
            case 57 : // textField_9
            {
                value = (java.lang.String)(((java.lang.String)field_DETAREAREA.getValue()));
                break;
            }
            case 54 : // subreport_1
            {
                value = (java.lang.String)(((java.lang.String)parameter_escalas_valorativas.getValue()));
                break;
            }
            case 55 : // variable_DETAREESTCODIGO_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 56 : // variableInitialValue_DETAREESTCODIGO_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 61 : // textField_13
            {
                value = (java.util.Date)(new Date());
                break;
            }
            case 48 : // textField_5
            {
                value = (java.lang.String)(((java.lang.String)field_DETAREGRUPO.getValue()));
                break;
            }
            case 43 : // group_DETAREESTCODIGO
            {
                value = (java.lang.Object)(((java.lang.String)field_DETAREESTCODIGO.getValue()));
                break;
            }
            case 45 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)field_DETARESEDE.getValue()));
                break;
            }
            case 53 : // connection_1
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 52 : // image_1
            {
                value = (java.awt.Image)((java.awt.Image)it.businesslogic.ireport.chart.DefaultChartFactory.drawChart(new String[]{"antialias=true","tooltips=true","legend=false","chartName=Bar","plotOrientation=2","foregroundAlpha=8.99","valueLabel=Escala Valorativa","subtitle=","plotBackground=[255,255,255]","quality=2","height=227","titlePosition=1","chartBackground=[255,255,255]","width=548","depthFactor=0.2","serie2=SERIE_ESCALA VALORATIVA","serie1=SERIE_AREAS","serie0=SERIE_ESCALA VALORATIVA","categoryLabel=nreas","title=GRnFICO ESTADnSTICO DE EVALUACInN DE nREAS POR ESTUDIANTE"}, (it.businesslogic.ireport.IReportScriptlet)((net.sf.jasperreports.engine.JRAbstractScriptlet)parameter_REPORT_SCRIPTLET.getValue())));
                break;
            }
            case 37 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 41 : // variable_SERIE_ESCALA VALORATIVA
            {
                value = (java.lang.String)(((java.lang.String)field_DETARECODEVAL.getValue()));
                break;
            }
            case 34 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 33 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 44 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_DETAREINSTITUCION.getValue()));
                break;
            }
            case 46 : // textField_3
            {
                value = (java.lang.String)(((java.lang.String)field_DETAREJORNADA.getValue()));
                break;
            }
            case 42 : // variable_SERIE_AREAS
            {
                value = (java.lang.String)(((java.lang.String)field_DETAREAREA.getValue()));
                break;
            }
            case 31 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 58 : // textField_10
            {
                value = (java.lang.String)(((java.lang.String)field_DETAREEVAL.getValue()));
                break;
            }
            case 36 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 50 : // textField_7
            {
                value = (java.lang.String)(""+((java.lang.String)field_DETAREAPELLIDOS.getValue())+" "+((java.lang.String)field_DETARENOMBRES.getValue())+" ");
                break;
            }
            case 35 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 60 : // textField_12
            {
                value = (java.lang.String)(" " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 39 : // variable_test
            {
                value = (java.lang.String)("test");
                break;
            }
            case 49 : // textField_6
            {
                value = (java.lang.String)(((java.lang.String)field_DETARENUMDOC.getOldValue()));
                break;
            }
            case 51 : // textField_8
            {
                value = (java.lang.String)("EVALUACInN DE nREAS POR ESTUDIANTE PERIODO "+((java.lang.String)field_DETAREPERIODO.getOldValue()));
                break;
            }
            case 38 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 40 : // variableInitialValue_test
            {
                value = (java.lang.String)("test");
                break;
            }
            case 32 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 47 : // textField_4
            {
                value = (java.lang.String)(((java.lang.String)field_DETAREGRADO.getOldValue()));
                break;
            }
            case 59 : // textField_11
            {
                value = (java.lang.String)("Pngina " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()) + " de ");
                break;
            }
            case 57 : // textField_9
            {
                value = (java.lang.String)(((java.lang.String)field_DETAREAREA.getOldValue()));
                break;
            }
            case 54 : // subreport_1
            {
                value = (java.lang.String)(((java.lang.String)parameter_escalas_valorativas.getValue()));
                break;
            }
            case 55 : // variable_DETAREESTCODIGO_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 56 : // variableInitialValue_DETAREESTCODIGO_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 61 : // textField_13
            {
                value = (java.util.Date)(new Date());
                break;
            }
            case 48 : // textField_5
            {
                value = (java.lang.String)(((java.lang.String)field_DETAREGRUPO.getOldValue()));
                break;
            }
            case 43 : // group_DETAREESTCODIGO
            {
                value = (java.lang.Object)(((java.lang.String)field_DETAREESTCODIGO.getOldValue()));
                break;
            }
            case 45 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)field_DETARESEDE.getOldValue()));
                break;
            }
            case 53 : // connection_1
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 52 : // image_1
            {
                value = (java.awt.Image)((java.awt.Image)it.businesslogic.ireport.chart.DefaultChartFactory.drawChart(new String[]{"antialias=true","tooltips=true","legend=false","chartName=Bar","plotOrientation=2","foregroundAlpha=8.99","valueLabel=Escala Valorativa","subtitle=","plotBackground=[255,255,255]","quality=2","height=227","titlePosition=1","chartBackground=[255,255,255]","width=548","depthFactor=0.2","serie2=SERIE_ESCALA VALORATIVA","serie1=SERIE_AREAS","serie0=SERIE_ESCALA VALORATIVA","categoryLabel=nreas","title=GRnFICO ESTADnSTICO DE EVALUACInN DE nREAS POR ESTUDIANTE"}, (it.businesslogic.ireport.IReportScriptlet)((net.sf.jasperreports.engine.JRAbstractScriptlet)parameter_REPORT_SCRIPTLET.getValue())));
                break;
            }
            case 37 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 41 : // variable_SERIE_ESCALA VALORATIVA
            {
                value = (java.lang.String)(((java.lang.String)field_DETARECODEVAL.getOldValue()));
                break;
            }
            case 34 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 33 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 44 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_DETAREINSTITUCION.getOldValue()));
                break;
            }
            case 46 : // textField_3
            {
                value = (java.lang.String)(((java.lang.String)field_DETAREJORNADA.getOldValue()));
                break;
            }
            case 42 : // variable_SERIE_AREAS
            {
                value = (java.lang.String)(((java.lang.String)field_DETAREAREA.getOldValue()));
                break;
            }
            case 31 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 58 : // textField_10
            {
                value = (java.lang.String)(((java.lang.String)field_DETAREEVAL.getOldValue()));
                break;
            }
            case 36 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 50 : // textField_7
            {
                value = (java.lang.String)(""+((java.lang.String)field_DETAREAPELLIDOS.getOldValue())+" "+((java.lang.String)field_DETARENOMBRES.getOldValue())+" ");
                break;
            }
            case 35 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 60 : // textField_12
            {
                value = (java.lang.String)(" " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 39 : // variable_test
            {
                value = (java.lang.String)("test");
                break;
            }
            case 49 : // textField_6
            {
                value = (java.lang.String)(((java.lang.String)field_DETARENUMDOC.getValue()));
                break;
            }
            case 51 : // textField_8
            {
                value = (java.lang.String)("EVALUACInN DE nREAS POR ESTUDIANTE PERIODO "+((java.lang.String)field_DETAREPERIODO.getValue()));
                break;
            }
            case 38 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 40 : // variableInitialValue_test
            {
                value = (java.lang.String)("test");
                break;
            }
            case 32 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 47 : // textField_4
            {
                value = (java.lang.String)(((java.lang.String)field_DETAREGRADO.getValue()));
                break;
            }
            case 59 : // textField_11
            {
                value = (java.lang.String)("Pngina " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()) + " de ");
                break;
            }
            case 57 : // textField_9
            {
                value = (java.lang.String)(((java.lang.String)field_DETAREAREA.getValue()));
                break;
            }
            case 54 : // subreport_1
            {
                value = (java.lang.String)(((java.lang.String)parameter_escalas_valorativas.getValue()));
                break;
            }
            case 55 : // variable_DETAREESTCODIGO_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 56 : // variableInitialValue_DETAREESTCODIGO_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 61 : // textField_13
            {
                value = (java.util.Date)(new Date());
                break;
            }
            case 48 : // textField_5
            {
                value = (java.lang.String)(((java.lang.String)field_DETAREGRUPO.getValue()));
                break;
            }
            case 43 : // group_DETAREESTCODIGO
            {
                value = (java.lang.Object)(((java.lang.String)field_DETAREESTCODIGO.getValue()));
                break;
            }
            case 45 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)field_DETARESEDE.getValue()));
                break;
            }
            case 53 : // connection_1
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 52 : // image_1
            {
                value = (java.awt.Image)((java.awt.Image)it.businesslogic.ireport.chart.DefaultChartFactory.drawChart(new String[]{"antialias=true","tooltips=true","legend=false","chartName=Bar","plotOrientation=2","foregroundAlpha=8.99","valueLabel=Escala Valorativa","subtitle=","plotBackground=[255,255,255]","quality=2","height=227","titlePosition=1","chartBackground=[255,255,255]","width=548","depthFactor=0.2","serie2=SERIE_ESCALA VALORATIVA","serie1=SERIE_AREAS","serie0=SERIE_ESCALA VALORATIVA","categoryLabel=nreas","title=GRnFICO ESTADnSTICO DE EVALUACInN DE nREAS POR ESTUDIANTE"}, (it.businesslogic.ireport.IReportScriptlet)((net.sf.jasperreports.engine.JRAbstractScriptlet)parameter_REPORT_SCRIPTLET.getValue())));
                break;
            }
            case 37 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 41 : // variable_SERIE_ESCALA VALORATIVA
            {
                value = (java.lang.String)(((java.lang.String)field_DETARECODEVAL.getValue()));
                break;
            }
            case 34 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 33 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 44 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_DETAREINSTITUCION.getValue()));
                break;
            }
            case 46 : // textField_3
            {
                value = (java.lang.String)(((java.lang.String)field_DETAREJORNADA.getValue()));
                break;
            }
            case 42 : // variable_SERIE_AREAS
            {
                value = (java.lang.String)(((java.lang.String)field_DETAREAREA.getValue()));
                break;
            }
            case 31 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 58 : // textField_10
            {
                value = (java.lang.String)(((java.lang.String)field_DETAREEVAL.getValue()));
                break;
            }
            case 36 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 50 : // textField_7
            {
                value = (java.lang.String)(""+((java.lang.String)field_DETAREAPELLIDOS.getValue())+" "+((java.lang.String)field_DETARENOMBRES.getValue())+" ");
                break;
            }
            case 35 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 60 : // textField_12
            {
                value = (java.lang.String)(" " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
