/*
 * Generated by JasperReports - 5/06/06 03:27 PM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import java.util.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class ReporteNo3 extends JRCalculator
{


    /**
     *
     */
    private JRFillParameter parameter_estudiante = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_usuario = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_escalas_valorativas = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;

    private JRFillField field_DETASIGCODGRUPO = null;
    private JRFillField field_DETASIGGRUPO = null;
    private JRFillField field_DETASIGPERIODO = null;
    private JRFillField field_DETASIGSEDE = null;
    private JRFillField field_DETASIGID = null;
    private JRFillField field_DETASIGESTCODIGO = null;
    private JRFillField field_DETASIGCODGRADO = null;
    private JRFillField field_DETASIGNOMBRES = null;
    private JRFillField field_DETASIGAPELLIDOS = null;
    private JRFillField field_DETASIGGRADO = null;
    private JRFillField field_DETASIGEVAL = null;
    private JRFillField field_DETASIGINSTITUCION = null;
    private JRFillField field_DETASIGASIGNATURA = null;
    private JRFillField field_DETASIGCODEVAL = null;
    private JRFillField field_DETASIGNUMDOC = null;
    private JRFillField field_DETASIGCODJERARASIGNATURA = null;
    private JRFillField field_DETASIGJORNADA = null;

    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_test = null;
    private JRFillVariable variable_SERIE_ASIGNATURAS = null;
    private JRFillVariable variable_SERIE_ESCALA32VALORATIVA = null;
    private JRFillVariable variable_DETASIGESTCODIGO_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        ) throws JRException
    {
        parameter_estudiante = (JRFillParameter)parsm.get("estudiante");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)parsm.get("REPORT_RESOURCE_BUNDLE");
        parameter_usuario = (JRFillParameter)parsm.get("usuario");
        parameter_REPORT_CONNECTION = (JRFillParameter)parsm.get("REPORT_CONNECTION");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)parsm.get("REPORT_PARAMETERS_MAP");
        parameter_escalas_valorativas = (JRFillParameter)parsm.get("escalas_valorativas");
        parameter_REPORT_LOCALE = (JRFillParameter)parsm.get("REPORT_LOCALE");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)parsm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)parsm.get("REPORT_SCRIPTLET");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)parsm.get("REPORT_MAX_COUNT");

        field_DETASIGCODGRUPO = (JRFillField)fldsm.get("DETASIGCODGRUPO");
        field_DETASIGGRUPO = (JRFillField)fldsm.get("DETASIGGRUPO");
        field_DETASIGPERIODO = (JRFillField)fldsm.get("DETASIGPERIODO");
        field_DETASIGSEDE = (JRFillField)fldsm.get("DETASIGSEDE");
        field_DETASIGID = (JRFillField)fldsm.get("DETASIGID");
        field_DETASIGESTCODIGO = (JRFillField)fldsm.get("DETASIGESTCODIGO");
        field_DETASIGCODGRADO = (JRFillField)fldsm.get("DETASIGCODGRADO");
        field_DETASIGNOMBRES = (JRFillField)fldsm.get("DETASIGNOMBRES");
        field_DETASIGAPELLIDOS = (JRFillField)fldsm.get("DETASIGAPELLIDOS");
        field_DETASIGGRADO = (JRFillField)fldsm.get("DETASIGGRADO");
        field_DETASIGEVAL = (JRFillField)fldsm.get("DETASIGEVAL");
        field_DETASIGINSTITUCION = (JRFillField)fldsm.get("DETASIGINSTITUCION");
        field_DETASIGASIGNATURA = (JRFillField)fldsm.get("DETASIGASIGNATURA");
        field_DETASIGCODEVAL = (JRFillField)fldsm.get("DETASIGCODEVAL");
        field_DETASIGNUMDOC = (JRFillField)fldsm.get("DETASIGNUMDOC");
        field_DETASIGCODJERARASIGNATURA = (JRFillField)fldsm.get("DETASIGCODJERARASIGNATURA");
        field_DETASIGJORNADA = (JRFillField)fldsm.get("DETASIGJORNADA");

        variable_PAGE_NUMBER = (JRFillVariable)varsm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)varsm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)varsm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)varsm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)varsm.get("COLUMN_COUNT");
        variable_test = (JRFillVariable)varsm.get("test");
        variable_SERIE_ASIGNATURAS = (JRFillVariable)varsm.get("SERIE_ASIGNATURAS");
        variable_SERIE_ESCALA32VALORATIVA = (JRFillVariable)varsm.get("SERIE_ESCALA VALORATIVA");
        variable_DETASIGESTCODIGO_COUNT = (JRFillVariable)varsm.get("DETASIGESTCODIGO_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 1480 : // textField_4
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGGRADO.getValue()));
                break;
            }
            case 1465 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1470 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1491 : // textField_10
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGEVAL.getValue()));
                break;
            }
            case 1493 : // textField_12
            {
                value = (java.lang.String)(" " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 1481 : // textField_5
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGGRUPO.getValue()));
                break;
            }
            case 1482 : // textField_6
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGNUMDOC.getValue()));
                break;
            }
            case 1489 : // variableInitialValue_DETASIGESTCODIGO_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1474 : // variable_SERIE_ASIGNATURAS
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGASIGNATURA.getValue()));
                break;
            }
            case 1484 : // textField_8
            {
                value = (java.lang.String)("EVALUACInN DE ASIGNATURAS POR ESTUDIANTE PERIODO "+((java.lang.String)field_DETASIGPERIODO.getValue()));
                break;
            }
            case 1478 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGSEDE.getValue()));
                break;
            }
            case 1475 : // variable_SERIE_ESCALA VALORATIVA
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGCODEVAL.getValue()));
                break;
            }
            case 1466 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1490 : // textField_9
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGASIGNATURA.getValue()));
                break;
            }
            case 1485 : // image_1
            {
                value = (java.awt.Image)((java.awt.Image)it.businesslogic.ireport.chart.DefaultChartFactory.drawChart(new String[]{"antialias=true","tooltips=true","legend=false","chartName=Bar","plotOrientation=2","foregroundAlpha=0.99","valueLabel=Escala Valorativa","subtitle=","plotBackground=[255,255,255]","quality=2","height=227","titlePosition=1","chartBackground=[255,255,255]","width=548","depthFactor=0.2","serie2=SERIE_ESCALA VALORATIVA","serie1=SERIE_ASIGNATURAS","serie0=SERIE_ESCALA VALORATIVA","categoryLabel=Asignaturas","title=GRnFICO ESTADnSTICO DE EVALUACInN DE ASIGNATURAS POR ESTUDIANTE"}, (it.businesslogic.ireport.IReportScriptlet)((net.sf.jasperreports.engine.JRAbstractScriptlet)parameter_REPORT_SCRIPTLET.getValue())));
                break;
            }
            case 1477 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGINSTITUCION.getValue()));
                break;
            }
            case 1486 : // connection_1
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 1479 : // textField_3
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGJORNADA.getValue()));
                break;
            }
            case 1468 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1488 : // variable_DETASIGESTCODIGO_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1494 : // textField_13
            {
                value = (java.util.Date)(new Date());
                break;
            }
            case 1469 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1476 : // group_DETASIGESTCODIGO
            {
                value = (java.lang.Object)(((java.lang.String)field_DETASIGESTCODIGO.getValue()));
                break;
            }
            case 1472 : // variable_test
            {
                value = (java.lang.String)("test");
                break;
            }
            case 1487 : // subreport_1
            {
                value = (java.lang.String)(((java.lang.String)parameter_escalas_valorativas.getValue()));
                break;
            }
            case 1471 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1464 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1467 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1483 : // textField_7
            {
                value = (java.lang.String)(""+((java.lang.String)field_DETASIGAPELLIDOS.getValue())+" "+((java.lang.String)field_DETASIGNOMBRES.getValue())+" ");
                break;
            }
            case 1492 : // textField_11
            {
                value = (java.lang.String)("Pngina " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()) + " de ");
                break;
            }
            case 1473 : // variableInitialValue_test
            {
                value = (java.lang.String)("test");
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 1480 : // textField_4
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGGRADO.getOldValue()));
                break;
            }
            case 1465 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1470 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1491 : // textField_10
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGEVAL.getOldValue()));
                break;
            }
            case 1493 : // textField_12
            {
                value = (java.lang.String)(" " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 1481 : // textField_5
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGGRUPO.getOldValue()));
                break;
            }
            case 1482 : // textField_6
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGNUMDOC.getOldValue()));
                break;
            }
            case 1489 : // variableInitialValue_DETASIGESTCODIGO_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1474 : // variable_SERIE_ASIGNATURAS
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGASIGNATURA.getOldValue()));
                break;
            }
            case 1484 : // textField_8
            {
                value = (java.lang.String)("EVALUACInN DE ASIGNATURAS POR ESTUDIANTE PERIODO "+((java.lang.String)field_DETASIGPERIODO.getOldValue()));
                break;
            }
            case 1478 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGSEDE.getOldValue()));
                break;
            }
            case 1475 : // variable_SERIE_ESCALA VALORATIVA
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGCODEVAL.getOldValue()));
                break;
            }
            case 1466 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1490 : // textField_9
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGASIGNATURA.getOldValue()));
                break;
            }
            case 1485 : // image_1
            {
                value = (java.awt.Image)((java.awt.Image)it.businesslogic.ireport.chart.DefaultChartFactory.drawChart(new String[]{"antialias=true","tooltips=true","legend=false","chartName=Bar","plotOrientation=2","foregroundAlpha=0.99","valueLabel=Escala Valorativa","subtitle=","plotBackground=[255,255,255]","quality=2","height=227","titlePosition=1","chartBackground=[255,255,255]","width=548","depthFactor=0.2","serie2=SERIE_ESCALA VALORATIVA","serie1=SERIE_ASIGNATURAS","serie0=SERIE_ESCALA VALORATIVA","categoryLabel=Asignaturas","title=GRnFICO ESTADnSTICO DE EVALUACInN DE ASIGNATURAS POR ESTUDIANTE"}, (it.businesslogic.ireport.IReportScriptlet)((net.sf.jasperreports.engine.JRAbstractScriptlet)parameter_REPORT_SCRIPTLET.getValue())));
                break;
            }
            case 1477 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGINSTITUCION.getOldValue()));
                break;
            }
            case 1486 : // connection_1
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 1479 : // textField_3
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGJORNADA.getOldValue()));
                break;
            }
            case 1468 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1488 : // variable_DETASIGESTCODIGO_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1494 : // textField_13
            {
                value = (java.util.Date)(new Date());
                break;
            }
            case 1469 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1476 : // group_DETASIGESTCODIGO
            {
                value = (java.lang.Object)(((java.lang.String)field_DETASIGESTCODIGO.getOldValue()));
                break;
            }
            case 1472 : // variable_test
            {
                value = (java.lang.String)("test");
                break;
            }
            case 1487 : // subreport_1
            {
                value = (java.lang.String)(((java.lang.String)parameter_escalas_valorativas.getValue()));
                break;
            }
            case 1471 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1464 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1467 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1483 : // textField_7
            {
                value = (java.lang.String)(""+((java.lang.String)field_DETASIGAPELLIDOS.getOldValue())+" "+((java.lang.String)field_DETASIGNOMBRES.getOldValue())+" ");
                break;
            }
            case 1492 : // textField_11
            {
                value = (java.lang.String)("Pngina " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()) + " de ");
                break;
            }
            case 1473 : // variableInitialValue_test
            {
                value = (java.lang.String)("test");
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 1480 : // textField_4
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGGRADO.getValue()));
                break;
            }
            case 1465 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1470 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1491 : // textField_10
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGEVAL.getValue()));
                break;
            }
            case 1493 : // textField_12
            {
                value = (java.lang.String)(" " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 1481 : // textField_5
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGGRUPO.getValue()));
                break;
            }
            case 1482 : // textField_6
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGNUMDOC.getValue()));
                break;
            }
            case 1489 : // variableInitialValue_DETASIGESTCODIGO_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1474 : // variable_SERIE_ASIGNATURAS
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGASIGNATURA.getValue()));
                break;
            }
            case 1484 : // textField_8
            {
                value = (java.lang.String)("EVALUACInN DE ASIGNATURAS POR ESTUDIANTE PERIODO "+((java.lang.String)field_DETASIGPERIODO.getValue()));
                break;
            }
            case 1478 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGSEDE.getValue()));
                break;
            }
            case 1475 : // variable_SERIE_ESCALA VALORATIVA
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGCODEVAL.getValue()));
                break;
            }
            case 1466 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1490 : // textField_9
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGASIGNATURA.getValue()));
                break;
            }
            case 1485 : // image_1
            {
                value = (java.awt.Image)((java.awt.Image)it.businesslogic.ireport.chart.DefaultChartFactory.drawChart(new String[]{"antialias=true","tooltips=true","legend=false","chartName=Bar","plotOrientation=2","foregroundAlpha=0.99","valueLabel=Escala Valorativa","subtitle=","plotBackground=[255,255,255]","quality=2","height=227","titlePosition=1","chartBackground=[255,255,255]","width=548","depthFactor=0.2","serie2=SERIE_ESCALA VALORATIVA","serie1=SERIE_ASIGNATURAS","serie0=SERIE_ESCALA VALORATIVA","categoryLabel=Asignaturas","title=GRnFICO ESTADnSTICO DE EVALUACInN DE ASIGNATURAS POR ESTUDIANTE"}, (it.businesslogic.ireport.IReportScriptlet)((net.sf.jasperreports.engine.JRAbstractScriptlet)parameter_REPORT_SCRIPTLET.getValue())));
                break;
            }
            case 1477 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGINSTITUCION.getValue()));
                break;
            }
            case 1486 : // connection_1
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 1479 : // textField_3
            {
                value = (java.lang.String)(((java.lang.String)field_DETASIGJORNADA.getValue()));
                break;
            }
            case 1468 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1488 : // variable_DETASIGESTCODIGO_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1494 : // textField_13
            {
                value = (java.util.Date)(new Date());
                break;
            }
            case 1469 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1476 : // group_DETASIGESTCODIGO
            {
                value = (java.lang.Object)(((java.lang.String)field_DETASIGESTCODIGO.getValue()));
                break;
            }
            case 1472 : // variable_test
            {
                value = (java.lang.String)("test");
                break;
            }
            case 1487 : // subreport_1
            {
                value = (java.lang.String)(((java.lang.String)parameter_escalas_valorativas.getValue()));
                break;
            }
            case 1471 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1464 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1467 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1483 : // textField_7
            {
                value = (java.lang.String)(""+((java.lang.String)field_DETASIGAPELLIDOS.getValue())+" "+((java.lang.String)field_DETASIGNOMBRES.getValue())+" ");
                break;
            }
            case 1492 : // textField_11
            {
                value = (java.lang.String)("Pngina " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()) + " de ");
                break;
            }
            case 1473 : // variableInitialValue_test
            {
                value = (java.lang.String)("test");
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
