SELECT ROTDAGGJERGRADO, ROTDAGGDOCENTE, ROTDAGGASIGNATURA,ROTDAGGGRUPO,PERNOMBRE1||' '||PERNOMBRE2||' '||PERAPELLIDO1||' '||PERAPELLIDO2,ASINOMBRE
FROM ROT_DOC_ASIG_GRADO_GRUPO,PERSONAL,ASIGNATURA
where ROTDAGGJERGRADO in(
SELECT G_JERCODIGO 
FROM G_JERARQUIA
where G_JERTIPO=1
and G_JERNIVEL=7 
and G_JERINST=312
and G_JERSEDE=1
and G_JERJORN=2
and G_JERMETOD=1 
)
and PERNUMDOCUM like ROTDAGGDOCENTE
and ASICODINST=312
and ASICODMETOD=1
and ASIVIGENCIA=2007  
and ASICODIGO=ROTDAGGASIGNATURA

