drop TABLE INTEGRACION_LOG cascade constraints;

CREATE TABLE INTEGRACION_LOG
(
  ID       NUMBER(12)                           NOT NULL,
  FECHA    DATE                                 DEFAULT sysdate               NOT NULL,
  tipo     NUMBER(3)                            NOT NULL,
  mensaje  VARCHAR2(200)
);

DROP SEQUENCE SEQ_HIS_NOV_EST;

CREATE SEQUENCE SEQ_HIS_NOV_EST
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  ORDER;

DROP SEQUENCE SEQ_HIS_NOV_INST;

CREATE SEQUENCE SEQ_HIS_NOV_INST
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  ORDER;


DROP TABLE HISTORICO_NOVEDAD_ESTUDIANTE CASCADE CONSTRAINTS;

CREATE TABLE HISTORICO_NOVEDAD_ESTUDIANTE(
  HISNOVESTFECHA       DATE                     DEFAULT SYSDATE               NOT NULL,
  HISNOVESTCODIGO      NUMBER                   NOT NULL,
  HISNOVESTTIPO        NUMBER                   NOT NULL,
  HISNOVESTINST1       NUMBER,
  HISNOVESTINST2       NUMBER,
  HISNOVESTSEDE1       NUMBER,
  HISNOVESTSEDE2       NUMBER,
  HISNOVESTJORN1       NUMBER,
  HISNOVESTJORN2       NUMBER,
  HISNOVESTMETOD1      NUMBER,
  HISNOVESTMETOD2      NUMBER,
  HISNOVESTGRADO1      NUMBER,
  HISNOVESTGRADO2      NUMBER,
  HISNOVESTGRUPO1      NUMBER,
  HISNOVESTGRUPO2      NUMBER,
  HISNOVESTSEDENOMBRE  VARCHAR2(100 BYTE),
  HISNOVESTESTCODIGO   NUMBER(20)               NOT NULL,
  HISNOVESTINSNOMBRE   VARCHAR2(100 BYTE)
);


DROP TABLE HISTORICO_NOVEDAD_INSTITUCION CASCADE CONSTRAINTS;

CREATE TABLE HISTORICO_NOVEDAD_INSTITUCION
(
  HISNOVINSFECHA       DATE                     DEFAULT SYSDATE               NOT NULL,
  HISNOVINSTIPO        NUMBER                   NOT NULL,
  HISNOVINSCODIGO      NUMBER                   NOT NULL,
  HISNOVINSINSCODIGO1  NUMBER,
  HISNOVINSINSCODIGO2  NUMBER,
  HISNOVINSCODIGO1     NUMBER,
  HISNOVINSCODIGO2     NUMBER,
  HISNOVINSNOMBRE1     VARCHAR2(100 BYTE),
  HISNOVINSNOMBRE2     VARCHAR2(100 BYTE)
);

CREATE TABLE NOVEDAD_INTEGRACION(
  ID         NUMBER(6)                          NOT NULL,
  CATEGORIA  NUMBER(1)                          NOT NULL,
  FUNCION    NUMBER(2)                          NOT NULL,
  FECHA      DATE                               DEFAULT SYSDATE               NOT NULL,
  ESTADO     NUMBER(1)                          DEFAULT 0                     NOT NULL,
  MENSAJE    VARCHAR2(200 BYTE),
  P1         VARCHAR2(200 BYTE),
  P2         VARCHAR2(200 BYTE),
  P3         VARCHAR2(200 BYTE),
  P4         VARCHAR2(200 BYTE),
  P5         VARCHAR2(200 BYTE),
  P6         VARCHAR2(200 BYTE),
  P7         VARCHAR2(200 BYTE),
  P8         VARCHAR2(200 BYTE),
  P9         VARCHAR2(200 BYTE),
  P10        VARCHAR2(200 BYTE),
  P11        VARCHAR2(200 BYTE),
  P12        VARCHAR2(200 BYTE),
  P13        VARCHAR2(200 BYTE),
  P14        VARCHAR2(200 BYTE),
  P15        VARCHAR2(200 BYTE),
  P16        VARCHAR2(200 BYTE),
  P17        VARCHAR2(200 BYTE),
  P18        VARCHAR2(200 BYTE),
  P19        VARCHAR2(200 BYTE),
  P20        VARCHAR2(200 BYTE),
  P21        VARCHAR2(200 BYTE),
  P22        VARCHAR2(200 BYTE),
  P23        VARCHAR2(200 BYTE)
);

--constraint de unicidad   
CREATE UNIQUE INDEX NOVEDAD_INTEGRACION_PK ON NOVEDAD_INTEGRACION
(ID, CATEGORIA, FUNCION)
LOGGING
NOPARALLEL;

--llave primaria  
ALTER TABLE NOVEDAD_INTEGRACION ADD (
  CONSTRAINT NOVEDAD_INTEGRACION_PK
 PRIMARY KEY
 (ID, CATEGORIA, FUNCION));


	