CREATE TABLE NOVEDAD_INTEGRACION(
  ID         NUMBER(6)                          NOT NULL,
  CATEGORIA  NUMBER(1)                          NOT NULL,
  FUNCION    NUMBER(2)                          NOT NULL,
  FECHA      DATE                               DEFAULT SYSDATE               NOT NULL,
  ESTADO     NUMBER(1)                          DEFAULT 0                     NOT NULL,
  MENSAJE    VARCHAR2(200 BYTE),
  P1         VARCHAR2(200 BYTE),
  P2         VARCHAR2(200 BYTE),
  P3         VARCHAR2(200 BYTE),
  P4         VARCHAR2(200 BYTE),
  P5         VARCHAR2(200 BYTE),
  P6         VARCHAR2(200 BYTE),
  P7         VARCHAR2(200 BYTE),
  P8         VARCHAR2(200 BYTE),
  P9         VARCHAR2(200 BYTE),
  P10        VARCHAR2(200 BYTE),
  P11        VARCHAR2(200 BYTE),
  P12        VARCHAR2(200 BYTE),
  P13        VARCHAR2(200 BYTE),
  P14        VARCHAR2(200 BYTE),
  P15        VARCHAR2(200 BYTE),
  P16        VARCHAR2(200 BYTE),
  P17        VARCHAR2(200 BYTE),
  P18        VARCHAR2(200 BYTE),
  P19        VARCHAR2(200 BYTE),
  P20        VARCHAR2(200 BYTE),
  P21        VARCHAR2(200 BYTE),
  P22        VARCHAR2(200 BYTE),
  P23        VARCHAR2(200 BYTE)
);

CREATE UNIQUE INDEX NOVEDAD_INTEGRACION_PK ON NOVEDAD_INTEGRACION
(ID, CATEGORIA, FUNCION);

ALTER TABLE NOVEDAD_INTEGRACION ADD (
  CONSTRAINT NOVEDAD_INTEGRACION_PK
 PRIMARY KEY
 (ID, CATEGORIA, FUNCION));