CREATE TABLE INTEGRACION_DUC_LOG
(
  ID       NUMBER(12)                           NOT NULL,
  FECHA    DATE                                 DEFAULT SYSDATE               NOT NULL,
  tipo     NUMBER(3)                            NOT NULL,
  mensaje  VARCHAR2(200)
);



CREATE SEQUENCE SEQ_HIS_NOV_INST
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  ORDER;

CREATE TABLE HISTORICO_NOVEDAD_INSTITUCION
(
  HISNOVINSFECHA       DATE                     DEFAULT SYSDATE               NOT NULL,
  HISNOVINSTIPO        NUMBER                   NOT NULL,
  HISNOVINSCODIGO      NUMBER                   NOT NULL,
  HISNOVINSINSCODIGO1  NUMBER,
  HISNOVINSINSCODIGO2  NUMBER,
  HISNOVINSCODIGO1     NUMBER,
  HISNOVINSCODIGO2     NUMBER,
  HISNOVINSNOMBRE1     VARCHAR2(100 BYTE),
  HISNOVINSNOMBRE2     VARCHAR2(100 BYTE)
);
  
